services:
  back-end:
    build:
      context: Back-End
      dockerfile: Dockerfile
    ports:
      - 8019:8019
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres-db/tododb
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: abc123
    depends_on:
      - postgres-db
  front-end:
    build:
      context: Front-End/todo-app
      dockerfile: Dockerfile
    ports:
      - 8020:3006
    depends_on:
      - back-end
  front-end-admin:
    build: 
      context: Front-End/todo-admin-app
      dockerfile: Dockerfile
    ports:
      - 8021:3000
    depends_on:
      - back-end
  postgres-db:
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DATABASE: tododb
      POSTGRES_PASSWORD: abc123
volumes:
  db: