server:
  port: 8019

spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tododb
    username: postgres
    password: abc123
#  sql:
#    init:
#      mode: embedded
#      data-locations: classpath:/data.sql
#  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    properties:
      hibernate.format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true

  #Mail Setup
  mail:
    host: smtp.googlemail.com
    port: 587
    username: contact.lwind@gmail.com
    password: tvbjuiwkzxoiivha
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#Jwt Setup
jwtSecret: hcmute999
jwtExpirationMs: 6000000
jwtCookieName: babysharkdodododo




#logging:
#  pattern:
#  level:
#    org.hibernate.orm.jdbc.bind: trace